apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fq3i
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-fq3i@sha256:5205f3a4abe91b74e59240f9daf932b6f163be51cd7a783d365d6c3f27cf804a
        name: my-nodejs
        resources: {}
status: {}
